version: '3.8'

services:
  postgres-db:
    image: postgres:13 # Usa a imagem oficial do PostgreSQL versão 13
    container_name: gemini_postgres_db
    environment:
      - POSTGRES_USER=admin          # Usuário do banco
      - POSTGRES_PASSWORD=admin      # Senha do banco
      - POSTGRES_DB=projetogemini_db # Nome do banco de dados a ser criado
    ports:
      - "5435:5432" # Mapeia a porta do seu computador para a porta do container
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
